fix: remove old changelog
go-vela/vela-email pull request #7
Opened 2022-03-02 18:45 UTC by kaymckay

Remove old changelog code that interferes with github's new release notes generation

2022-03-02 19:57 UTC, wass3r requested changes
you'll want to remove https://github.com/go-vela/vela-email/blob/main/.github/workflows/release.yml as well

2022-03-02 20:11 UTC, kaymckay commented
@wass3r the whole file?

2022-03-09 15:31 UTC, wass3r approved these changes

2022-03-10 16:18 UTC, ecrupper approved these changes

2022-03-10 16:21 UTC, merged